# server config
server:
  port: 8018
  
# database config
spring:
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: C##WATER
    password: WATER
    
  redis:
    host: 127.0.0.1
    port: 6379
   
# file upload config
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
      location: C:/Users/hi/git/Mulbburi



# image upload directory
image: 
  image-dir: src/main/resources/upload/ 

      
# mybatis config
mybatis:
  mapper-locations: mappers/**/*.xml
